# -*- coding: utf-8 -*-
"""Project 1.Movie Recommendation System using Machine Learning with python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeCwbQPFSZ1G98Uo8WDQ5Xi-HFdIs_8e

Importing the dependencies (importing the libraries)
"""

import numpy as np
import pandas as pd
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

"""Data Collection and Pre-Processing"""

# loading the data from csv file to pandas dataframe
movies_data = pd.read_csv('/content/movies.csv')

# printing the first 5 rows of the dataframe
movies_data.head()

#number of rows and columns in my dataframe
movies_data.shape

#selecting the relevant features(feature selection) for recommendation
selected_features = ['genres','keywords','tagline','cast','director']
print(selected_features)

# replacing the null values(missing values) with null string

for feature in selected_features:
  movies_data[feature] = movies_data[feature].fillna('')

# combining all the 5 selected features

combined_features = movies_data['genres']+' '+movies_data['keywords']+' '+movies_data['tagline']+' '+movies_data['cast']+' '+movies_data['director']

print(combined_features)

# converting the text data to feature vectors

vectorizer = TfidfVectorizer()

feature_vectors = vectorizer.fit_transform(combined_features)

print(feature_vectors)



"""Cosine Similarity"""

# getting the similarity scores or confidence using cosine similarity

similarity = cosine_similarity(feature_vectors)

print(similarity)

print(similarity.shape)

"""Getting the movie name from the user"""

# getting the movie name from the user

movie_name = input("Enter your favorite movie name : ")

#creating a list with all the movie name present in the dataset

list_of_all_titles = movies_data['title'].tolist()
print(list_of_all_titles)

# finding the close match for the movie name given by the user

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)
print(find_close_match)

close_match = find_close_match[0]
print(close_match)

# finding the index of the movie with title

index_of_the_movie =movies_data[ movies_data.title == close_match]['index'].values[0]
print(index_of_the_movie)

# getting a list of similar movie with similarity score

similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

len(similarity_score)

# sorting the movies based on their similarity score

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sorted_similar_movies)

# print the name of similar movies based on the index

print("Movies suggested for you")

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index =movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

"""Movie Recommendation System"""

movie_name = input("Enter your favorite movie name : ")

list_of_all_titles = movies_data['title'].tolist()

find_close_match = difflib.get_close_matches(movie_name,list_of_all_titles)

close_match = find_close_match[0]

index_of_the_movie =movies_data[ movies_data.title == close_match]['index'].values[0]

similarity_score = list(enumerate(similarity[index_of_the_movie]))

sorted_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)

print("Movies suggested for you")

i = 1

for movie in sorted_similar_movies:
  index = movie[0]
  title_from_index =movies_data[movies_data.index==index]['title'].values[0]
  if (i<30):
    print(i, '.',title_from_index)
    i+=1

